apiVersion: v1
name: victoria-metrics-anomaly
description: Victoria Metrics Anomaly Detection - a service that continuously scans Victoria Metrics time series and detects unexpected changes within data patterns in real-time.
version: 0.3.0
appVersion: v1.0.0-beta
sources:
- https://github.com/VictoriaMetrics/helm-charts