config:
  reader:
    datasource_url: http://cluster-victoria-metrics-cluster-vmselect.default.svc.cluster.local:8481/select/
    queries:
      active_timeseries:
        expr: 'sum(vm_cache_entries{type="storage/hour_metric_ids"})'
      churn_rate:
        expr: 'sum(rate(vm_new_timeseries_created_total[5m]))'
      ingestion_rate:
        expr: 'sum(rate(vm_rows_inserted_total[5m])) by (type,accountID) > 0'
      insertion_rate:
        expr: 'sum(rate(vm_http_requests_total{path=~"/api/v1/write|.*insert.*"}[5m])) by (path) > 0'
      slow_inserts:
        expr: 'sum(rate(vm_slow_row_inserts_total[5m])) / sum(rate(vm_rows_inserted_total[5m]))'
  writer:
    datasource_url: http://cluster-victoria-metrics-cluster-vminsert.default.svc.cluster.local:8480/insert/

  monitoring:
    pull:
      enabled: true
      port: 8440
    push:
      url: "http://cluster-victoria-metrics-cluster-vminsert.default.svc.cluster.local:8480/insert/"
      extra_labels:
        job: "vmanomaly"

license:
  secret:
    name: "vmanomaly-license"
    key: "license"
