{{- $ctx := dict "helm" . }}
{{- $ns := include "vm.namespace" . }}
{{- range $name, $app := .Values }}
{{- if and (kindIs "map" $app) $app.enabled ($app.horizontalPodAutoscaler).enabled }}
{{- $hpa := $app.horizontalPodAutoscaler }}
{{- $_ := set $ctx "extraLabels" $app.extraLabels }}
{{- $_ := set $ctx "appKey" $name }}
{{- $fullname := include "vm.plain.fullname" $ctx }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels: {{ include "vm.labels" $ctx | nindent 4 }}
  name: {{ $fullname }}
  namespace: {{ $ns }}
spec:
  maxReplicas: {{ $hpa.maxReplicas }}
  minReplicas: {{ $hpa.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $fullname }}
  metrics: {{ toYaml $hpa.metrics | nindent 4 }}
  {{- with $hpa.behavior }}
  behavior: {{ toYaml . | nindent 4 }}
  {{- end -}}
{{- end }}
{{- end }}
