apiVersion: v2
name: crds
description: A subchart stores victoriametrics operator CRDs.
type: application
version: 0.0.0
appVersion: "0.0.0"
dependencies:
  - name: victoria-metrics-common
    version: "0.0.*"
    repository: https://victoriametrics.github.io/helm-charts
