{{- $zonesMap := include "per-zone-vmcluster.vmclusterSpec" . | fromYaml -}}
{{- range $zoneName, $rolloutZone := $zonesMap }}
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  {{- with $rolloutZone.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end  }}
  name: vmcluster-{{ $zoneName }}
  namespace: {{ include "vm.namespace" $ }}
  labels: {{ include "victoria-metrics-distributed.labels" $ | nindent 4 }}
spec:
{{- toYaml (deepCopy $rolloutZone) | nindent 2 }}
{{- end }}
