{{- if .Values.serviceAccount.create -}}
{{- $ctx := dict "helm" . }}
{{- $fullname := include "vm.plain.fullname" $ctx }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ (.Values.serviceAccount).name | default $fullname }}
  namespace: {{ include "vm.namespace" . }}
  labels: {{ include "vm.labels" $ctx | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
