vmstorage:
  podDisruptionBudget:
    enabled: true
  serviceMonitor:
    enabled: true
    annotations:
      annotationName: annotationValue
    extraLabels:
      labelName: labelValue
    basicAuth:
      password:
        name: basic-auth
        key: password
      username:
        name: basic-auth
        key: user
    relabelings:
    - sourceLabels: ["prometheus_replica"]
      regex: ".*"
      targetLabel: "another_prometheus_replica"
      action: replace
    metricRelabelings:
    - regex: "prometheus_replica"
      action: labeldrop

vmselect:
  podDisruptionBudget:
    enabled: true
  serviceMonitor:
    enabled: true
    annotations:
      annotationName: annotationValue
    extraLabels:
      labelName: labelValue
    basicAuth:
      password:
        name: basic-auth
        key: password
      username:
        name: basic-auth
        key: user
    relabelings:
    - sourceLabels: ["prometheus_replica"]
      regex: ".*"
      targetLabel: "another_prometheus_replica"
      action: replace
    metricRelabelings:
    - regex: "prometheus_replica"
      action: labeldrop

vminsert:
  podDisruptionBudget:
    enabled: true
  serviceMonitor:
    enabled: true
    annotations:
      annotationName: annotationValue
    extraLabels:
      labelName: labelValue
    basicAuth:
      password:
        name: basic-auth
        key: password
      username:
        name: basic-auth
        key: user
    relabelings:
    - sourceLabels: ["prometheus_replica"]
      regex: ".*"
      targetLabel: "another_prometheus_replica"
      action: replace
    metricRelabelings:
    - regex: "prometheus_replica"
      action: labeldrop

license:
#  key: "asdf"
  secret:
    name: "victoria-metrics-license"
    key: "license"
