apiVersion: v1
appVersion: v1.92.0
description: Victoria Metrics Single version - high-performance, cost-effective and scalable TSDB, long-term remote storage for Prometheus
name: victoria-metrics-single
version: 0.9.1
sources:
- https://github.com/VictoriaMetrics/helm-charts
