apiVersion: v2
type: application
description: VictoriaMetrics Single version - high-performance, cost-effective and scalable TSDB, long-term remote storage for Prometheus
name: victoria-metrics-single
version: 0.25.5
appVersion: v1.130.0
sources:
  - https://github.com/VictoriaMetrics/helm-charts
kubeVersion: ">=1.25.0-0"
keywords:
  - victoriametrics
  - vmsingle
  - single
  - monitoring
  - kubernetes
  - observability
  - tsdb
  - metrics
  - metricsql
  - timeseries
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/category: "monitoring-logging"
  artifacthub.io/links: |
    - name: Sources
      url: https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-operator
    - name: Charts repo
      url: https://victoriametrics.github.io/helm-charts/
    - name: Docs
      url: https://docs.victoriametrics.com/victoriametrics/single-server-victoriametrics/
    - name: Changelog
      url: https://docs.victoriametrics.com/victoriametrics/changelog/
dependencies:
  - name: victoria-metrics-common
    version: "0.0.*"
    repository: https://victoriametrics.github.io/helm-charts
