apiVersion: v1
appVersion: v1.91.3
description: Victoria Metrics Single version - high-performance, cost-effective and scalable TSDB, long-term remote storage for Prometheus
name: victoria-metrics-single
version: 0.8.64
sources:
- https://github.com/VictoriaMetrics/helm-charts
