{{- if and .Values.alertmanager.enabled .Values.alertmanager.templateFiles }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ printf "%s-%s" (include "victoria-metrics-k8s-stack.fullname" $) "alertmanager-extra-tpl" | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "vm.namespace" . }}
  labels: 
    app.kubernetes.io/component: {{ include "victoria-metrics-k8s-stack.name" $ }}-alertmanager
{{ include "victoria-metrics-k8s-stack.labels" . | indent 4 }}
data:
{{- range $file, $template := .Values.alertmanager.templateFiles }}
  {{ $file }}: |-
     {{- $template | nindent 4 }}
{{- end }}
{{- end }}
