{{- if .Values.alertmanager.enabled }}
{{- if and .Values.alertmanager.spec.configRawYaml .Values.alertmanager.config }}
{{- fail "ERROR: Both .Values.alertmanager.spec.configRawYaml and .Values.alertmanager.config are set, but only one is allowed." }}
{{- end }}
{{- if and (not .Values.alertmanager.spec.configSecret) (not .Values.alertmanager.spec.configRawYaml) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "victoria-metrics-k8s-stack.fullname" . }}-alertmanager
  namespace: {{ .Release.Namespace }}
  labels: 
    app.kubernetes.io/component: {{ include "victoria-metrics-k8s-stack.name" $ }}-alertmanager
{{ include "victoria-metrics-k8s-stack.labels" . | indent 4 }}
stringData:
  alertmanager.yaml: {{ toYaml .Values.alertmanager.config | quote }}
{{- end }}
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanager
metadata:
  {{- with .Values.alertmanager.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end  }}
  name: {{ .Values.alertmanager.name | default (include "victoria-metrics-k8s-stack.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels: 
    app.kubernetes.io/component: {{ include "victoria-metrics-k8s-stack.name" $ }}-alertmanager
{{ include "victoria-metrics-k8s-stack.labels" . | indent 4 }}
spec:
{{ include "victoria-metrics-k8s-stack.alertmanagerSpec" . | indent 2}}
{{- end }}
