apiVersion: v1
appVersion: v1.91.3
description: Victoria Metrics Auth - is a simple auth proxy and router for VictoriaMetrics.
name: victoria-metrics-auth
version: 0.2.84
sources:
- https://github.com/VictoriaMetrics/helm-charts
