apiVersion: v2
type: application
appVersion: v1.105.0
description: Victoria Metrics Auth - is a simple auth proxy and router for VictoriaMetrics.
name: victoria-metrics-auth
version: 0.7.3
sources:
  - https://github.com/VictoriaMetrics/helm-charts
icon: https://avatars.githubusercontent.com/u/43720803?s=200&v=4
kubeVersion: ">=1.25.0-0"
home: https://github.com/VictoriaMetrics/helm-charts
keywords:
  - victoriametrics
  - vmauth
  - auth
  - proxy
  - router
  - balancer
  - monitoring
  - kubernetes
  - observability
  - metrics
  - timeseries
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/category: "monitoring-logging"
  artifacthub.io/links: |
    - name: Sources
      url: https://github.com/VictoriaMetrics/helm-charts
    - name: Charts repo
      url: https://victoriametrics.github.io/helm-charts/
    - name: Docs
      url: https://docs.victoriametrics.com/vmauth
dependencies:
  - name: victoria-metrics-common
    version: "0.0.*"
    repository: https://victoriametrics.github.io/helm-charts
