apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "victoria-logs-collector.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "victoria-logs-collector.fullname" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "victoria-logs-collector.fullname" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "victoria-logs-collector.fullname" . }}
        {{- with .Values.podLabels }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
        {{- if not .Values.native }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- end }}
    spec:
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      serviceAccountName: {{ include "victoria-logs-collector.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{ omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: victoria-logs-collector
          image: {{ include "victoria-logs-collector.image" . }}
          imagePullPolicy: IfNotPresent
          {{- if .Values.securityContext.enabled }}
          securityContext: {{ omit .Values.securityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.resources }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.native }}
          args: {{ include "victoria-logs-collector.args" . | nindent 12 }}
          {{- end }}
          env:
            - name: VECTOR_SELF_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            {{- with .Values.env }}
            {{ toYaml . | nindent 12}}
            {{- end }}
          volumeMounts:
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: varlog
              mountPath: /var/log
              readOnly: true
              # /var/lib is needed in environments like Minikube, where logs may symlink to /var/lib paths.
            - name: varlib
              mountPath: /var/lib
              readOnly: true
            {{- if not .Values.native }}
            - name: config
              mountPath: /etc/vector
              readOnly: true
            {{- end }}
            - name: vl-collector-data
              mountPath: /vl-collector
      volumes:
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlib
          hostPath:
            path: /var/lib
        {{- if not .Values.native }}
        - name: config
          configMap:
            name: {{ include "victoria-logs-collector.fullname" . }}-config
        {{- end }}
        - name: vl-collector-data
          hostPath:
            path: /var/lib/vl-collector
