{{- $ctx := dict "helm" . }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "vm.fullname" $ctx }}
  namespace: {{ include "vm.namespace" . }}
  labels: {{ include "vm.labels" $ctx | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "vm.selectorLabels" $ctx | nindent 6 }}
  template:
    metadata:
      {{- $_ := set $ctx "extraLabels" .Values.podLabels }}
      labels: {{ include "vm.podLabels" $ctx | nindent 8 }}
      {{- $_ := unset $ctx "extraLabels" }}
      {{- $annotations := deepCopy .Values.podAnnotations }}
      {{- if not .Values.native }}
      {{- $_ := set $annotations "checksum/config" (include (print .Template.BasePath "/configmap.yaml") . | sha256sum) }}
      {{- end }}
      annotations: {{ toYaml $annotations | nindent 8 }}
    spec:
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      serviceAccountName: {{ include "vm.fullname" $ctx }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{ omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- with (.Values.imagePullSecrets | default (.Values.global).imagePullSecrets) }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: victoria-logs-collector
          image: {{ include "victoria-logs-collector.image" $ctx }}
          imagePullPolicy: IfNotPresent
          {{- if .Values.securityContext.enabled }}
          securityContext: {{ omit .Values.securityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.resources }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.native }}
          ports:
            - name: http
              containerPort: 9429
              protocol: TCP
          args: {{ include "victoria-logs-collector.args" . | nindent 12 }}
          {{- end }}
          env:
            - name: VECTOR_SELF_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            {{- with .Values.env }}
            {{ toYaml . | nindent 12}}
            {{- end }}
          volumeMounts:
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: varlog
              mountPath: /var/log
              readOnly: true
              # /var/lib is needed in environments like Minikube, where logs may symlink to /var/lib paths.
            - name: varlib
              mountPath: /var/lib
              readOnly: true
            {{- if not .Values.native }}
            - name: config
              mountPath: /etc/vector
              readOnly: true
            {{- end }}
            - name: vl-collector-data
              mountPath: /vl-collector
      volumes:
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlib
          hostPath:
            path: /var/lib
        {{- if not .Values.native }}
        - name: config
          configMap:
            name: {{ include "vm.fullname" $ctx }}-config
        {{- end }}
        - name: vl-collector-data
          hostPath:
            path: /var/lib/vl-collector
