{{- $ctx := dict "helm" . }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "vm.fullname" $ctx }}
  labels: {{ include "vm.labels" $ctx | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes", "namespaces", "pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vm.fullname" $ctx }}
  labels: {{ include "vm.labels" $ctx | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "vm.fullname" $ctx }}
    namespace: {{ include "vm.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "vm.fullname" $ctx }}
  apiGroup: rbac.authorization.k8s.io
