{{- $ctx := dict "helm" . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vm.fullname" $ctx }}
  namespace: {{ include "vm.namespace" . }}
  labels: {{ include "vm.labels" $ctx | nindent 4 }}
  annotations: {{ toYaml .Values.serviceAccount.annotations | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
