apiVersion: v2
type: application
description: Victoria Metrics Gateway - Auth & Rate-Limitting proxy for Victoria Metrics
name: victoria-metrics-gateway
version: 0.5.2
appVersion: v1.104.0
sources:
  - https://github.com/VictoriaMetrics/helm-charts
icon: https://avatars.githubusercontent.com/u/43720803?s=200&v=4
kubeVersion: ">=1.25.0-0"
home: https://github.com/VictoriaMetrics/helm-charts
keywords:
  - victoriametrics
  - vmgateway
  - auth
  - proxy
  - gateway
  - router
  - balancer
  - monitoring
  - kubernetes
  - observability
  - metrics
  - timeseries
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/category: "monitoring-logging"
  artifacthub.io/links: |
    - name: Sources
      url: https://github.com/VictoriaMetrics/helm-charts
    - name: Charts repo
      url: https://victoriametrics.github.io/helm-charts/
    - name: Docs
      url: https://docs.victoriametrics.com/vmgateway
dependencies:
  - name: victoria-metrics-common
    version: "0.0.*"
    repository: https://victoriametrics.github.io/helm-charts
