apiVersion: v2
type: application
appVersion: v0.5.1
description: The VictoriaTraces single Helm chart deploys VictoriaTraces database in Kubernetes.
name: victoria-traces-single
version: 0.0.4
sources:
  - https://github.com/VictoriaMetrics/helm-charts
icon: https://avatars.githubusercontent.com/u/43720803?s=200&v=4
kubeVersion: ">=1.25.0-0"
home: https://github.com/VictoriaMetrics/helm-charts
keywords:
  - victoriametrics
  - victoriatraces
  - traces
  - kubernetes
  - observability
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/category: "monitoring-logging"
  artifacthub.io/links: |
    - name: Sources
      url: https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-traces-single
    - name: Charts repo
      url: https://victoriametrics.github.io/helm-charts/
    - name: Docs
      url: https://docs.victoriametrics.com/victoriatraces/
    - name: Changelog
      url: https://docs.victoriametrics.com/victoriatraces/changelog/
dependencies:
  - name: victoria-metrics-common
    version: "0.0.*"
    repository: https://victoriametrics.github.io/helm-charts/
