{{- $global := (dict "Values" (deepCopy .Values) "Release" (deepCopy .Release) "Chart" (deepCopy .Chart) "Template" (deepCopy .Template)) -}}
{{- $fullname := ((printf "%s-coredns" (include "victoria-metrics-k8s-stack.fullname" .)) | trunc 63 | trimSuffix "-") }}
{{- if .Values.coreDns.enabled }}
{{- if .Values.coreDns.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}
  namespace: kube-system
  {{- $extraLabels := dict "app" $fullname "jobLabel" "coredns" }}
  {{- $ctx := merge (deepCopy $global) (dict "extraLabels" $extraLabels) }}
  labels: {{ include "victoria-metrics-k8s-stack.labels" $ctx | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: {{ .Values.coreDns.service.port }}
      protocol: TCP
      targetPort: {{ .Values.coreDns.service.targetPort }}
  {{- with .Values.coreDns.service.selector }}
  selector: {{ toYaml . | nindent 4 }}
  {{- end}}
{{- end }}
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: {{ $fullname }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "victoria-metrics-k8s-stack.labels" . | nindent 4 }}
spec:
  {{- omit .Values.coreDns.spec "selector" "namespaceSelector" | toYaml | nindent 2 }}
  selector:
    matchLabels:
      app: {{ $fullname }}
      app.kubernetes.io/instance: {{ default .Release.Name .Values.argocdReleaseOverride | trunc 63 | trimSuffix "-" }}
  namespaceSelector:
    matchNames:
      - "kube-system"
{{- end }}
