{{- if (index .Values "kube-state-metrics" "enabled") }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: {{ printf "%s-%s" (include "victoria-metrics-k8s-stack.fullname" $) "kube-state-metrics" | trunc 63 | trimSuffix "-" }}
  namespace: {{ $.Release.Namespace }}
  labels: {{ include "victoria-metrics-k8s-stack.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kube-state-metrics.name" (index .Subcharts "kube-state-metrics") }}
      app.kubernetes.io/instance: {{ default $.Release.Name $.Values.argocdReleaseOverride | quote }}
{{- if empty (index .Values "kube-state-metrics" "vmServiceScrape" "spec") }}
  endpoints:
  - port: http
    honorLabels: true
    metricRelabelConfigs:
      - action: labeldrop
        regex: (uid|container_id|image_id)
  jobLabel: app.kubernetes.io/name
{{ else }}
{{- if not (hasKey (index .Values "kube-state-metrics" "vmServiceScrape" "spec") "endpoints") }}
  endpoints:
  - port: http
{{- end }}
{{ omit (index .Values "kube-state-metrics" "vmServiceScrape" "spec") "selector" | toYaml | indent 2 }}
{{- end }}
{{- end }}
