
{{- if .Values.kubeEtcd.enabled }}
{{- if .Values.kubeEtcd.endpoints }}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ printf "%s-%s" (include "victoria-metrics-k8s-stack.fullname" $) "kube-etcd" | trunc 63 | trimSuffix "-" }}
  namespace: kube-system 
  labels: 
    app: {{ include "victoria-metrics-k8s-stack.fullname" . }}-kube-etcd
    k8s-app: etcd-server
{{ include "victoria-metrics-k8s-stack.labels" . | indent 4 }}
subsets:
  - addresses:
      {{- range .Values.kubeEtcd.endpoints }}
      - ip: {{ . }}
      {{- end }}
    ports:
      - name: http-metrics
        port: {{ .Values.kubeEtcd.service.port }}
        protocol: TCP
{{- end }}
{{- if .Values.kubeEtcd.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" (include "victoria-metrics-k8s-stack.fullname" $) "kube-etcd" | trunc 63 | trimSuffix "-" }}
  namespace: kube-system
  labels:
    app: {{ include "victoria-metrics-k8s-stack.fullname" . }}-kube-etcd
    jobLabel: kube-etcd
{{ include "victoria-metrics-k8s-stack.labels" . | indent 4 }}
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: {{ .Values.kubeEtcd.service.port }}
      protocol: TCP
      targetPort: {{ .Values.kubeEtcd.service.targetPort }}
{{- if .Values.kubeEtcd.endpoints }}{{- else }}
  selector:
    {{- if .Values.kubeEtcd.service.selector }}
{{ toYaml .Values.kubeEtcd.service.selector | indent 4 }}
    {{- else}}
    component: etcd
    {{- end}}
{{- end }}
  type: ClusterIP
{{- end }}
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: {{ printf "%s-%s" (include "victoria-metrics-k8s-stack.fullname" $) "kube-etcd" | trunc 63 | trimSuffix "-" }}
  namespace: {{ $.Release.Namespace }}
  labels: {{ include "victoria-metrics-k8s-stack.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "victoria-metrics-k8s-stack.fullname" . }}-kube-etcd
      app.kubernetes.io/instance: {{ default $.Release.Name $.Values.argocdReleaseOverride | quote }}
  namespaceSelector:
    matchNames:
      - "kube-system"
{{ omit .Values.kubeEtcd.spec "selector" "namespaceSelector" | toYaml | indent 2 }}
{{- end }}
