{{- $fullname := ((printf "%s-kube-state-metrics" (include "victoria-metrics-k8s-stack.fullname" .)) | trunc 63 | trimSuffix "-") }}
{{- $ksm := index .Values "kube-state-metrics" }}
{{- if $ksm.enabled }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: {{ $fullname }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "victoria-metrics-k8s-stack.labels" . | nindent 4 }}
spec:
  {{- with (omit $ksm.vmServiceScrape.spec "selector") }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kube-state-metrics.name" (index .Subcharts "kube-state-metrics") }}
      app.kubernetes.io/instance: {{ default .Release.Name .Values.argocdReleaseOverride | quote }}
  {{- if or (empty $ksm.vmServiceScrape.spec) (not (hasKey $ksm.vmServiceScrape.spec "endpoints")) }}
  endpoints:
  - port: http
    honorLabels: true
    metricRelabelConfigs:
      - action: labeldrop
        regex: (uid|container_id|image_id)
  jobLabel: app.kubernetes.io/name
  {{- end }}
{{- end }}
