{{- $global := (dict "Values" (deepCopy .Values) "Release" (deepCopy .Release) "Chart" (deepCopy .Chart) "Template" (deepCopy .Template)) -}}
{{- $fullname := ((printf "%s-kube-scheduler" (include "victoria-metrics-k8s-stack.fullname" .)) | trunc 63 | trimSuffix "-") }}
{{- if .Values.kubeScheduler.enabled }}
{{- if .Values.kubeScheduler.endpoints }}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ $fullname }}
  namespace: kube-system
  {{- $extraLabels := dict "app" $fullname "k8s-app" "kube-scheduler" }}
  {{- $ctx := merge (deepCopy $global) (dict "extraLabels" $extraLabels) }}
  labels: {{ include "victoria-metrics-k8s-stack.labels" $ctx | nindent 4 }}
subsets:
  - addresses:
      {{- range .Values.kubeScheduler.endpoints }}
      - ip: {{ . }}
      {{- end }}
    ports:
      - name: http-metrics
        port: {{ .Values.kubeScheduler.service.port }}
        protocol: TCP
{{- end }}
{{- if .Values.kubeScheduler.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}
  namespace: kube-system
  {{- $extraLabels := dict "app" $fullname "jobLabel" "kube-scheduler" }}
  {{- $ctx := merge (deepCopy $global) (dict "extraLabels" $extraLabels) }}
  labels: {{ include "victoria-metrics-k8s-stack.labels" $ctx | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: {{ .Values.kubeScheduler.service.port }}
      protocol: TCP
      targetPort: {{ .Values.kubeScheduler.service.targetPort }}
  {{- if (empty .Values.kubeScheduler.endpoints) }}
  {{- with .Values.kubeScheduler.service.selector }}
  selector: {{ toYaml . | nindent 4 }}
  {{- end}}
  {{- end }}
  type: ClusterIP
{{- end }}
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: {{ $fullname }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "victoria-metrics-k8s-stack.labels" . | nindent 4 }}
spec:
  {{- omit .Values.kubeScheduler.spec "selector" "namespaceSelector" | toYaml | nindent 2 }}
  selector:
    matchLabels:
      app: {{ $fullname }}
      app.kubernetes.io/instance: {{ default .Release.Name .Values.argocdReleaseOverride | trunc 63 | trimSuffix "-" }}
  namespaceSelector:
    matchNames:
      - "kube-system"
{{- end }}
