remoteWriteUrls:
  - http://cluster-victoria-metrics-cluster-vminsert.default.svc.cluster.local:8480/insert/0/prometheus/

replicaCount: 3
deployment:
  enabled: false
statefulset:
  enabled: true
  clusterMode: true
  replicationFactor: 2
env:
  - name: ENV_VAR
    value: "just make sure that env var works"
