{{ if and .Values.vmsingle.enabled .Values.vmsingle.ingress.enabled -}}
{{- $servicePort := 8429 -}}
{{- $ingressPath := .Values.vmsingle.ingress.path -}}
{{- $serviceName := printf "%s-%s" "vmsingle" (include "victoria-metrics-k8s-stack.fullname" .) | trunc 63 | trimSuffix "-" }}
{{- $ingressPathType := .Values.vmsingle.ingress.pathType | default "" -}}
{{- $extraPaths := .Values.vmsingle.ingress.extraPaths -}}
{{- $newAPI := .Capabilities.APIVersions.Has "networking.k8s.io/v1" -}}
{{- if $newAPI -}}
apiVersion: networking.k8s.io/v1
{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ .Values.vmsingle.name | default $serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: {{ include "victoria-metrics-k8s-stack.name" $ }}-vmsingle
{{ include "victoria-metrics-k8s-stack.labels" . | indent 4 }}
{{- if .Values.vmsingle.ingress.labels }}
{{ toYaml .Values.vmsingle.ingress.labels | indent 4 }}
{{- end }}
  {{- if .Values.vmsingle.ingress.annotations }}
  annotations:
    {{- range $key, $value := .Values.vmsingle.ingress.annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.vmsingle.ingress.ingressClassName }}
  ingressClassName: {{ .Values.vmsingle.ingress.ingressClassName }}
  {{- end -}}
{{- if .Values.vmsingle.ingress.tls }}
  tls:
{{ tpl (toYaml .Values.vmsingle.ingress.tls) $ | indent 4 }}
{{- end }}
  rules:
  {{- if .Values.vmsingle.ingress.hosts  }}
  {{- range .Values.vmsingle.ingress.hosts }}
    - host: {{ tpl . $}}
      http:
        paths:
{{- if $extraPaths }}
{{ toYaml $extraPaths | indent 10 }}
{{- end }}
          - path: {{ $ingressPath }}
            {{- if $newAPI }}
            pathType: {{ $ingressPathType }}
            {{- end }}
            backend:
              {{- if $newAPI }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
              {{- end }}
  {{- end }}
  {{- else }}
    - http:
        paths:
          - backend:
              {{- if $newAPI }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
            pathType: {{ $ingressPathType }}
              {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
              {{- end }}
          {{- if $ingressPath }}
            path: {{ $ingressPath }}
            {{- end }}
  {{- end -}}
{{- end }}
