{{- if .Values.service.enabled -}}
{{- $ctx := dict "helm" . }}
apiVersion: v1
kind: Service
metadata:
  {{- with .Values.service.annotations }}
  annotations: {{ toYaml . | nindent 4}}
  {{- end }}
  {{- $_ := set $ctx "extraLabels" .Values.service.extraLabels }}
  labels: {{ include "vm.labels" $ctx | nindent 4 }}
  {{- $_ := unset $ctx "extraLabels" }}
  name: {{ include "vm.plain.fullname" $ctx }}
  namespace: {{ include "vm.namespace" . }}
spec:
  {{- with .Values.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- with .Values.service.externalIPs }}
  externalIPs: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{ toYaml . | nindent 4 }}
  {{- end }}
  type: {{ .Values.service.type }}
  {{- with .Values.service.healthCheckNodePort }}
  healthCheckNodePort: {{ . }}
  {{- end }}
  {{- with .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.ipFamilies }}
  ipFamilies: {{ toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.service.servicePort }}
      protocol: TCP
      targetPort: http
      {{- with .Values.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
    {{- with .Values.extraArgs.graphiteListenAddr }}
    - name: graphite-tcp
      protocol: TCP
      port: {{ include "vm.port.from.flag" (dict "flag" .) }}
      targetPort: graphite-tcp
    - name: graphite-udp
      protocol: UDP
      port: {{ include "vm.port.from.flag" (dict "flag" .) }}
      targetPort: graphite-udp
    {{- end }}
    {{- with .Values.extraArgs.influxListenAddr }}
    - name: influx-tcp
      protocol: TCP
      port: {{ include "vm.port.from.flag" (dict "flag" .) }}
      targetPort: influx-tcp
    - name: influx-udp
      protocol: UDP
      port: {{ include "vm.port.from.flag" (dict "flag" .) }}
      targetPort: influx-udp
    {{- end }}
    {{- with .Values.extraArgs.opentsdbHTTPListenAddr }}
    - name: opentsdbhttp
      port: {{ include "vm.port.from.flag" (dict "flag" .) }}
      targetPort: opentsdbhttp
    {{- end }}
    {{- with .Values.extraArgs.opentsdbListenAddr }}
    - name: opentsdb-udp
      protocol: UDP
      port: {{ include "vm.port.from.flag" (dict "flag" .) }}
      targetPort: opentsdb-udp
    - name: opentsdb-tcp
      protocol: TCP
      port: {{ include "vm.port.from.flag" (dict "flag" .) }}
      targetPort: opentsdb-tcp
    {{- end }}
  selector: {{ include "vm.selectorLabels" $ctx | nindent 4 }}
{{- end }}
