apiVersion: v1
name: victoria-metrics-agent
description: Victoria Metrics Agent - collects metrics from various sources and stores them to VictoriaMetrics
version: 0.9.2
appVersion: v1.92.1
sources:
- https://github.com/VictoriaMetrics/helm-charts
