apiVersion: v2
type: application
name: victoria-metrics-agent
description: Victoria Metrics Agent - collects metrics from various sources and stores them to VictoriaMetrics
version: 0.14.2
appVersion: v1.104.0
sources:
  - https://github.com/VictoriaMetrics/helm-charts
icon: https://avatars.githubusercontent.com/u/43720803?s=200&v=4
kubeVersion: ">=1.25.0-0"
home: https://github.com/VictoriaMetrics/helm-charts
keywords:
  - victoriametrics
  - vmagent
  - agent
  - collector
  - monitoring
  - kubernetes
  - observability
  - metrics
  - timeseries
  - servicediscovery
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/category: "monitoring-logging"
  artifacthub.io/links: |
    - name: Sources
      url: https://github.com/VictoriaMetrics/helm-charts
    - name: Charts repo
      url: https://victoriametrics.github.io/helm-charts/
    - name: Docs
      url: https://docs.victoriametrics.com/vmagent
dependencies:
  - name: victoria-metrics-common
    version: "0.0.*"
    repository: https://victoriametrics.github.io/helm-charts
