{{- $service := .Values.service }}
{{- if $service.enabled -}}
{{- $ctx := dict "helm" . }}
{{- $fullname := include "vm.plain.fullname" $ctx }}
{{- $ns := include "vm.namespace" $ctx }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vm.fullname" $ctx }}
  namespace: {{ include "vm.namespace" $ctx }}
  {{- with $service.annotations }}
  annotations: {{ toYaml . | nindent 4}}
  {{- end }}
  {{- $_ := set $ctx "extraLabels" $service.extraLabels }}
  labels: {{ include "vm.labels" $ctx | nindent 4 }}
  {{- $_ := unset $ctx "extraLabels" }}
spec:
  {{- with $service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- with $service.externalIPs }}
  externalIPs: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with $service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with $service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{ toYaml . | nindent 4 }}
  {{- end }}
  type: {{ $service.type }}
  {{- with $service.healthCheckNodePort }}
  healthCheckNodePort: {{ . }}
  {{- end }}
  {{- with $service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with $service.internalTrafficPolicy }}
  internalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with $service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with $service.ipFamilies }}
  ipFamilies: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with $service.trafficDistribution }}
  trafficDistribution: {{ . }}
  {{- end }}
  ports:
    - port: 9429
      targetPort: http
      protocol: TCP
      name: http
    {{- with (index .Values.extraArgs "syslog.listenAddr.udp") }}
    - name: syslog-udp
      protocol: UDP
      port: {{ include "vm.port.from.flag" (dict "flag" .) }}
      targetPort: syslog-udp
    {{- end }}
    {{- with (index .Values.extraArgs "syslog.listenAddr.tcp") }}
    - name: syslog-tcp
      protocol: TCP
      port: {{ include "vm.port.from.flag" (dict "flag" .) }}
      targetPort: syslog-tcp
    {{- end }}
  {{- $_ := set $ctx "extraLabels" (mergeOverwrite (deepCopy (.Values.selectorLabels | default dict)) (deepCopy $service.selectorLabels)) }}
  selector: {{ include "vm.selectorLabels" $ctx | nindent 4 }}
  {{- $_ := unset $ctx "extraLabels" }}
{{- end }}
