{{- $ctx := dict "helm" . }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "vm.fullname" $ctx }}
  namespace: {{ include "vm.namespace" $ctx }}
  {{- $_ := set $ctx "extraLabels" .Values.extraLabels }}
  labels: {{ include "vm.labels" $ctx | nindent 4 }}
  {{- $_ := unset $ctx "extraLabels" }}
  {{- with .Values.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels: {{ include "vm.selectorLabels" $ctx | nindent 6 }}
  serviceName: {{ include "vm.fullname" $ctx }}
  template:
    metadata:
      {{- $_ := set $ctx "extraLabels" .Values.podLabels }}
      labels: {{ include "vm.podLabels" $ctx | nindent 8 }}
      {{- $_ := unset $ctx "extraLabels" }}
      annotations: {{ toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{ omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: vlagent
          image: {{ include "vm.image" $ctx }}
          imagePullPolicy: IfNotPresent
          {{- if .Values.securityContext.enabled }}
          securityContext: {{ omit .Values.securityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.resources }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
          {{- end }}
          args: {{- include "vlagent.args" . | nindent 12 }}
          {{- with .Values.env }}
          env: {{- toYaml . | nindent 12}}
          {{- end }}
          volumeMounts:
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: vl-agent-data
              mountPath: /vlagent-data
            {{- include "vm.license.mount" . | nindent 12 }}
      volumes:
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.persistentVolume.enabled }}
          {{- if .Values.persistentVolume.existingClaim }}
        - name: vl-agent-data
          persistentVolumeClaim:
            claimName: {{ tpl .Values.persistentVolume.existingClaim $ctx }}
          {{- end }}
        {{- else }}
        - name: vl-agent-data
          emptyDir: {}
        {{- end }}
        {{- include "vm.license.volume" . | nindent 8 }}
  {{- $pvc := .Values.persistentVolume }}
  {{- if and $pvc.enabled (not $pvc.existingClaim) }}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: vl-agent-data
        {{- $_ := set $ctx "extraLabels" $pvc.extraLabels }}
        labels: {{ include "vm.labels" $ctx | nindent 10 }}
        {{- $_ := unset $ctx "extraLabels" }}
        {{- with $pvc.annotations  }}
        annotations: {{ toYaml . | nindent 10 }}
        {{- end }}
      spec:
        {{- with $pvc.accessModes }}
        accessModes: {{ toYaml . | nindent 10 }}
        {{- end }}
        resources:
          requests:
            storage: {{ $pvc.size }}
        {{- with $pvc.storageClassName }}
        storageClassName: {{ . }}
        {{- end }}
        {{- with $pvc.matchLabels }}
        selector:
          matchLabels: {{ toYaml . | nindent 12 }}
        {{- end }}
  {{- end }}
