{{- $Values := (.helm).Values | default .Values }}
condition: '{{ true }}'
name: k8s.rules.container_memory_limits
rules:
- condition: '{{ true }}'
  expr: |-
    kube_pod_container_resource_limits{resource="memory",job="kube-state-metrics"}  * on (namespace,pod,{{ $Values.global.clusterLabel }})
    group_left() max by (namespace,pod,{{ $Values.global.clusterLabel }}) (
      (kube_pod_status_phase{phase=~"Pending|Running"} == 1)
    )
  record: cluster:namespace:pod_memory:active:kube_pod_container_resource_limits
- condition: '{{ true }}'
  expr: |-
    sum by (namespace,{{ $Values.global.clusterLabel }}) (
        sum by (namespace,pod,{{ $Values.global.clusterLabel }}) (
            max by (namespace,pod,container,{{ $Values.global.clusterLabel }}) (
              kube_pod_container_resource_limits{resource="memory",job="kube-state-metrics"}
            ) * on (namespace,pod,{{ $Values.global.clusterLabel }}) group_left() max by (namespace,pod,{{ $Values.global.clusterLabel }}) (
              kube_pod_status_phase{phase=~"Pending|Running"} == 1
            )
        )
    )
  record: namespace_memory:kube_pod_container_resource_limits:sum
