{{- if .Values.vmcluster.enabled }}
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  {{- with .Values.vmcluster.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end  }}
  name: {{ .Values.vmcluster.name | default (include "victoria-metrics-k8s-stack.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "victoria-metrics-k8s-stack.labels" . | nindent 4 }}
spec:
{{ .Values.vmcluster.spec | toYaml | indent 2 }}

{{- $newAPI := .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" -}}
{{ if .Values.vmcluster.ingress.storage.enabled }}
---
{{- with .Values.vmcluster.ingress.storage }}
{{- $servicePort := $.Values.vmcluster.spec.vmstorage.port | default 8482 -}}
{{- $serviceName := printf "%s-%s" "vmstorage" (include "victoria-metrics-k8s-stack.fullname" $) | trunc 63 | trimSuffix "-" }}
{{- $ingressPath := .path -}}
{{- $ingressPathType := .pathType | default "" -}}
{{- $extraPaths := .extraPaths -}}
{{- if $newAPI -}}
apiVersion: networking.k8s.io/v1
{{- else if $.Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $serviceName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/component: {{ include "victoria-metrics-k8s-stack.name" $ }}-vmcluster
{{ include "victoria-metrics-k8s-stack.labels" $ | indent 4 }}
{{- if .labels }}
{{ toYaml .labels | indent 4 }}
{{- end }}
  {{- if .annotations }}
  annotations:
    {{- range $key, $value := .annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if .ingressClassName }}
  ingressClassName: {{ .ingressClassName }}
  {{- end -}}
{{- if .tls }}
  tls:
{{ tpl (toYaml .tls) $ | indent 4 }}
{{- end }}
  rules:
  {{- if .hosts  }}
  {{- range .hosts }}
    - host: {{ tpl . $}}
      http:
        paths:
{{- if $extraPaths }}
{{ toYaml $extraPaths | indent 10 }}
{{- end }}
          - path: {{ $ingressPath }}
            {{- if $newAPI }}
            pathType: {{ $ingressPathType }}
            {{- end }}
            backend:
              {{- if $newAPI }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
              {{- end }}
  {{- end }}
  {{- else }}
    - http:
        paths:
          - backend:
              {{- if $newAPI }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
            pathType: {{ $ingressPathType }}
              {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
              {{- end }}
          {{- if $ingressPath }}
            path: {{ $ingressPath }}
            {{- end }}
  {{- end -}}
{{- end }}
{{- end }}
{{ if .Values.vmcluster.ingress.select.enabled -}}
---
{{- with .Values.vmcluster.ingress.select }}
{{- $servicePort := $.Values.vmcluster.spec.vmselect.port | default 8481 -}}
{{- $serviceName := printf "%s-%s" "vmselect" (include "victoria-metrics-k8s-stack.fullname" $) | trunc 63 | trimSuffix "-" }}
{{- $ingressPath := .path -}}
{{- $ingressPathType := .pathType | default "" -}}
{{- $extraPaths := .extraPaths -}}
{{- if $newAPI -}}
apiVersion: networking.k8s.io/v1
{{- else if $.Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $serviceName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/component: {{ include "victoria-metrics-k8s-stack.name" $ }}-vmcluster
{{ include "victoria-metrics-k8s-stack.labels" $ | indent 4 }}
{{- if .labels }}
{{ toYaml .labels | indent 4 }}
{{- end }}
  {{- if .annotations }}
  annotations:
    {{- range $key, $value := .annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if .ingressClassName }}
  ingressClassName: {{ .ingressClassName }}
  {{- end -}}
{{- if .tls }}
  tls:
{{ tpl (toYaml .tls) $ | indent 4 }}
{{- end }}
  rules:
  {{- if .hosts  }}
  {{- range .hosts }}
    - host: {{ tpl . $}}
      http:
        paths:
{{- if $extraPaths }}
{{ toYaml $extraPaths | indent 10 }}
{{- end }}
          - path: {{ $ingressPath }}
            {{- if $newAPI }}
            pathType: {{ $ingressPathType }}
            {{- end }}
            backend:
              {{- if $newAPI }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
              {{- end }}
  {{- end }}
  {{- else }}
    - http:
        paths:
          - backend:
              {{- if $newAPI }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
            pathType: {{ $ingressPathType }}
              {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
              {{- end }}
          {{- if $ingressPath }}
            path: {{ $ingressPath }}
            {{- end }}
  {{- end -}}
{{- end }}
{{- end }}
{{ if .Values.vmcluster.ingress.insert.enabled -}}
---
{{- with .Values.vmcluster.ingress.insert }}
{{- $servicePort := $.Values.vmcluster.spec.vminsert.port | default 8480 -}}
{{- $serviceName := printf "%s-%s" "vminsert" (include "victoria-metrics-k8s-stack.fullname" $) | trunc 63 | trimSuffix "-" }}
{{- $ingressPath := .path -}}
{{- $ingressPathType := .pathType | default "" -}}
{{- $extraPaths := .extraPaths -}}
{{- if $newAPI -}}
apiVersion: networking.k8s.io/v1
{{- else if $.Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $serviceName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/component: {{ include "victoria-metrics-k8s-stack.name" $ }}-vmcluster
{{ include "victoria-metrics-k8s-stack.labels" $ | indent 4 }}
{{- if .labels }}
{{ toYaml .labels | indent 4 }}
{{- end }}
  {{- if .annotations }}
  annotations:
    {{- range $key, $value := .annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if .ingressClassName }}
  ingressClassName: {{ .ingressClassName }}
  {{- end -}}
{{- if .tls }}
  tls:
{{ tpl (toYaml .tls) $ | indent 4 }}
{{- end }}
  rules:
  {{- if .hosts  }}
  {{- range .hosts }}
    - host: {{ tpl . $}}
      http:
        paths:
{{- if $extraPaths }}
{{ toYaml $extraPaths | indent 10 }}
{{- end }}
          - path: {{ $ingressPath }}
            {{- if $newAPI }}
            pathType: {{ $ingressPathType }}
            {{- end }}
            backend:
              {{- if $newAPI }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
              {{- end }}
  {{- end }}
  {{- else }}
    - http:
        paths:
          - backend:
              {{- if $newAPI }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
            pathType: {{ $ingressPathType }}
              {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
              {{- end }}
          {{- if $ingressPath }}
            path: {{ $ingressPath }}
            {{- end }}
  {{- end -}}
{{- end }}
{{- end }}
{{- end }}

