{{- if .Values.podDisruptionBudget.enabled }}
{{- $ctx := dict "helm" . "appKey" "server" }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "vm.plain.fullname" $ctx }}
  namespace: {{ include "vm.namespace" . }}
  {{- $_ := set $ctx "extraLabels" .Values.podDisruptionBudget.labels }}
  labels: {{ include "vm.metaLabels" $ctx | nindent 4 }}
  {{- $_ := unset $ctx "extraLabels" }}
spec:
  {{- with .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
  {{- with .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
  selector:
    matchLabels: {{ include "vm.selectorLabels" $ctx | nindent 6 }}
{{- end }}
