{{- $app := .Values.server }}
{{- if and $app.enabled $app.ingress.enabled  }}
{{- $ctx := dict "helm" . "appKey" "server" }}
{{- $serviceName := include "vm.plain.fullname" $ctx }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- with $app.ingress.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- $_ := set $ctx "extraLabels" $app.ingress.extraLabels }}
  labels: {{ include "vm.labels" $ctx | nindent 4 }}
  name: {{ $serviceName }}
  namespace: {{ include "vm.namespace" . }}
spec:
  {{- with $app.ingress.ingressClassName }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with $app.ingress.tls }}
  tls: {{ tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  rules:
    {{- range $host := $app.ingress.hosts }}
    {{- $paths := ternary (list $host.path) $host.path (kindIs "string" $host.path) }}
    - host: {{ tpl $host.name $ }}
      http:
        paths:
          {{- range $path := $paths }}
          - path: {{ $path }}
            {{- with $app.ingress.pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              service:
                name: {{ $serviceName }}
                port: {{ include "vm.ingress.port" $host | nindent 18 }}
          {{- end }}
    {{- end }}
{{- end }}
