{{- $app := (.Values).server | default dict }}
{{- $vector := (.Values).vector | default dict }}
{{- $defaultConfig := $vector.customConfigName }}
{{- if and (or $vector.enabled $vector.customConfigNamespace) (has $defaultConfig $vector.existingConfigMaps) }}
  {{- $config := ($vector).customConfig | default dict }}
  {{- $ctx := dict "helm" . "appKey" "server" "style" "plain" }}
  {{- if $app.enabled }}
    {{- $port := int $app.service.servicePort -}}
    {{- range $sinkName, $sinkConfig := $config.sinks }}
      {{- if and $sinkConfig (eq $sinkConfig.type "elasticsearch") }}
        {{ if or (not $sinkConfig.endpoints) (kindIs "string" $sinkConfig.endpoints) }}
          {{- $_ := unset $config.sinks $sinkName }}
          {{- if (eq $app.mode "statefulSet") }}
            {{- range $i := until (int $app.replicaCount) }}
              {{- $_ := set $ctx "appIdx" $i }}
              {{- $url := printf "%s/insert/elasticsearch" (include "vm.url" $ctx) }}
              {{- $_ := set $sinkConfig "endpoints" (list $url) }}
              {{- $_ := set $config.sinks (printf "%s-%d" $sinkName $i) (deepCopy $sinkConfig) }}
            {{- end }}
          {{- else }}
            {{- $url := printf "%s/insert/elasticsearch" (include "vm.url" $ctx) }}
            {{- $_ := set $sinkConfig "endpoints" (list $url) }}
            {{- $_ := set $config.sinks $sinkName (deepCopy $sinkConfig) }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- $ns := include "vm.namespace" $ctx }}
  {{- $ns = ternary $ns (($vector).customConfigNamespace | default $ns) $vector.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $defaultConfig }}
  labels: {{ include "vm.labels" $ctx | nindent 4 }}
  namespace: {{ $ns }}
data:
  {{ include "vm.fullname" $ctx }}-vector.yaml: |{{ tpl (toYaml $config) . | nindent 4 }}
{{- end }}
