{{- $sa := .Values.serviceAccount }}
{{- $ctx := dict "helm" . "extraLabels" $sa.extraLabels }}
{{- if $sa.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels: {{ include "vm.metaLabels" $ctx | nindent 4 }}
  {{- with $sa.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "vm.sa.name" . }}
  namespace: {{ include "vm.namespace" . }}
{{- end }}
