{{- $app := .Values.vmselect }}
{{- if $app.enabled -}}
apiVersion: v1
kind: Service
metadata:
  {{- with $app.service.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- $ctx := merge (deepCopy .) (dict "extraLabels" $app.service.labels) }}
  labels: {{ include "victoria-metrics.vmselect.labels" $ctx | nindent 4 }}
  name: {{ template "victoria-metrics.vmselect.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- $clusterIP := ternary "None" $app.service.clusterIP $app.statefulSet.enabled }}
  {{- with $clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- $externalIPs := ternary (default list) $app.service.externalIPs $app.statefulSet.enabled }}
  {{- with $externalIPs }}
  externalIPs: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- $loadBalancerIP := ternary "" $app.service.loadBalancerIP $app.statefulSet.enabled }}
  {{- with $loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- $loadBalancerSourceRanges := ternary (default list) $app.service.loadBalancerSourceRanges $app.statefulSet.enabled }}
  {{- with $loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{ toYaml . | nindent 4 }}
  {{- end }}
  type: {{ ternary "ClusterIP" $app.service.type $app.statefulSet.enabled }}
  {{- with $app.service.healthCheckNodePort }}
  healthCheckNodePort: {{ . }}
  {{- end }}
  {{- with $app.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with $app.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with $app.service.ipFamilies }}
  ipFamilies: {{ toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - name: http
      port: {{ $app.service.servicePort }}
      protocol: TCP
      targetPort: {{ $app.service.targetPort }}
    {{- range $app.service.extraPorts }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: TCP
      targetPort: {{ .targetPort }}
    {{- end }}
    {{- with $app.extraArgs.clusternativeListenAddr }}
    - name: cluster-tcp
      protocol: TCP
      port: {{ include "split-host-port" . }}
      targetPort: cluster-tcp
    {{- end }}
  selector: {{ include "victoria-metrics.vmselect.matchLabels" . | nindent 4 }}
{{- end }}
