apiVersion: v1
appVersion: 0.17.2
description: Victoria Metrics Operator
name: victoria-metrics-operator
home: https://github.com/VictoriaMetrics/operator
sources:
- https://github.com/VictoriaMetrics/operator
version: 0.1.19
