## minimum set of parameters for vmgateway to run it as rate limiter
eula: true
clusterMode: true
auth:
  enable: true

read:
  url: http://cluster-victoria-metrics-cluster-vmselect.default.svc.cluster.local:8481
write:
  url:  http://cluster-victoria-metrics-cluster-vminsert.default.svc.cluster.local:8480

## Write Example
# kubectl port-forward svc/gateway-victoria-metrics-gateway 8431:8431
# curl 'http://127.0.0.1:8431/insert/0/prometheus/api/v1/import/prometheus' -X POST  -d 'foo{bar="baz1"} 123'

## Read Example
# kubectl port-forward svc/gateway-victoria-metrics-gateway 8431:8431
# curl 'http://localhost:8431/select/0/prometheus/api/v1/labels'

podDisruptionBudget:
  enabled: true
