{{- if ((.Values.extra).vmagent).enabled }}
{{- $urlCtx := dict "helm" . }}
{{- $_ := set $urlCtx "style" "managed" }}
{{- $ctx := dict "helm" . "appKey" (list "extra" "vmagent" "spec") -}}
{{- $values := .Values }}
{{- $spec := (($values.extra).vmagent).spec }}
{{- $zoneTpl := $values.zoneTpl }}
{{- $common := .Values.common }}
{{- $isMultitenant := $values.enableMultitenancy }}
{{- $tenant := ternary "multitenant" "0" $isMultitenant }}

{{- $urls := default list }}
{{- if $values.write.global.vmauth.enabled -}}
  {{- $write := deepCopy (($values.write).global).vmauth }}
  {{- $_ := set $write "spec" (mergeOverwrite (deepCopy $common.vmauth.spec) $write.spec) }}
  {{- $fullname := include "vm.fullname" . }}
  {{- $urlCtx := dict "helm" . "appKey" (list "globalWrite" "vmauth" "spec") "globalWrite" (dict "vmauth" $write) "style" "managed" "fullname" $fullname }}
  {{- $urls = append $urls (dict "url" (printf "%s/prometheus/api/v1/write" (include "vm.url" $urlCtx))) }}
{{- else }}
  {{- range $i, $z := $values.availabilityZones }}
    {{- $zone := mergeOverwrite (deepCopy $zoneTpl) $z }}
    {{- if $zone.vmcluster.enabled }}
      {{- $urlSpec := mergeOverwrite (deepCopy ((($common.vmcluster).spec | default dict))) (deepCopy ($zone.vmcluster).spec | default dict) }}
      {{- $_ := set $zone.vmcluster "spec" $urlSpec }}
      {{- $_ := set $urlCtx "zone" $zone }}
      {{- $_ := set $urlCtx "appKey" (list "zone" "vmcluster" "spec" "vminsert") }}
      {{- $urls = append $urls (dict "url" (printf "%s/insert/%s/prometheus/api/v1/write" (include "vm.url" $urlCtx) $tenant)) }}
    {{- else if $zone.vmsingle.enabled }}
      {{- $urlSpec := mergeOverwrite (deepCopy ((($common.vmsingle).spec | default dict))) (deepCopy ($zone.vmsingle).spec | default dict) }}
      {{- $_ := set $zone.vmsingle "spec" $urlSpec }}
      {{- $_ := set $urlCtx "zone" $zone }}
      {{- $_ := set $urlCtx "appKey" (list "zone" "vmsingle" "spec") }}
      {{- $urls = append $urls (dict "url" (printf "%s/prometheus/api/v1/write" (include "vm.url" $urlCtx))) }}
    {{- end }}
  {{- end }}
{{- end -}}

{{- $_ := set $spec "remoteWrite" (concat ($spec.remoteWrite | default list) $urls) }}
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  labels: {{ include "vm.labels" $ctx | nindent 4 }}
  name: {{ include "vm.cr.fullname" $ctx }}
  namespace: {{ include "vm.namespace" $ctx }}
spec: {{ tpl (toYaml $spec) . | nindent 2 }}
{{- $_ := unset $urlCtx "style" -}}
{{- end }}
