{{- $ctx := dict "helm" . }}
{{- $fullname := include "vm.fullname" . }}
{{- if ((((.Values).write).global).vmauth).enabled }}
  {{- $commonAuth := dict "spec" ((((.Values).common).vmauth).spec | default dict) }}
  {{- $auth := .Values.write.global.vmauth | default dict }}
  {{- $auth = mergeOverwrite (deepCopy $commonAuth) (deepCopy $auth) }}
  {{- $_ := set $ctx "appKey" (list "vmauth" "spec") }}
  {{- $_ := set $ctx "fullname" $fullname }}
  {{- $_ := set $ctx "vmauth" $auth }}
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAuth
metadata:
  name: {{ include "vm.cr.fullname" $ctx }}
  namespace: {{ include "vm.namespace" $ctx }}
  labels: {{ include "vm.labels" $ctx | nindent 4 }}
  {{- with ((((.Values).write).global).vmauth).annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end  }}
spec:
  {{- with (omit $auth.spec "unauthorizedUserAccessSpec") }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  unauthorizedUserAccessSpec:
    url_map:
      - src_paths:
          - "/api/v1/write"
          - "/prometheus/api/v1/write"
          - "/write"
          - "/api/v1/import"
          - "/api/v1/import/.+"
        {{- $_ := set $ctx "style" "managed" }}
        {{- $urls := default list }}
        {{- $commonAgentSpec := (((.Values).common).vmagent).spec | default dict }}
        {{- range $i, $z := $.Values.availabilityZones }}
          {{- $zone := mergeOverwrite (deepCopy $.Values.zoneTpl) $z }}
          {{- if $zone.vmagent.enabled -}}
            {{- $agentSpec := $zone.vmagent.spec | default dict }}
            {{- $_ := set $zone.vmagent "spec" (mergeOverwrite (deepCopy $commonAgentSpec) $agentSpec) }}
            {{- $_ := set $ctx "zone" $zone }}
            {{- $_ := set $ctx "appKey" (list "zone" "vmagent" "spec") }}
            {{- $urls = append $urls (include "vm.url" $ctx) }}
          {{- end -}}
        {{- end }}
        {{- $_ := unset $ctx "style" }}
        {{- if empty $urls }}
          {{- fail "No global vmauth write backend urls defined" -}}
        {{- end }}
        url_prefix: {{ toYaml $urls | nindent 10 }}
{{- end }}
