apiVersion: v2
type: application
description: VictoriaMetrics Operator CRDs
name: victoria-metrics-operator-crds
home: https://github.com/VictoriaMetrics/operator
sources:
  - https://github.com/VictoriaMetrics/helm-charts
  - https://github.com/VictoriaMetrics/operator
version: 0.5.0
appVersion: v0.63.0
icon: https://avatars.githubusercontent.com/u/43720803?s=200&v=4
kubeVersion: ">=1.25.0-0"
keywords:
  - victoriametrics
  - operator
  - monitoring
  - kubernetes
  - observability
  - tsdb
  - metrics
  - metricsql
  - timeseries
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/operator: "true"
  artifacthub.io/category: "monitoring-logging"
  artifacthub.io/links: |
    - name: Sources
      url: https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-operator
    - name: Charts repo
      url: https://victoriametrics.github.io/helm-charts/
    - name: Docs
      url: https://docs.victoriametrics.com/operator/
    - name: Changelog
      url: https://docs.victoriametrics.com/operator/changelog/
