apiVersion: v1
appVersion: 1.83.1
description: Victoria Metrics Cluster version - high-performance, cost-effective and scalable TSDB, long-term remote storage for Prometheus
name: victoria-metrics-cluster
version: 0.9.41
sources:
- https://github.com/VictoriaMetrics/helm-charts
