apiVersion: v1
appVersion: v1.91.3
description: Victoria Metrics Cluster version - high-performance, cost-effective and scalable TSDB, long-term remote storage for Prometheus
name: victoria-metrics-cluster
version: 0.9.74
sources:
- https://github.com/VictoriaMetrics/helm-charts
