apiVersion: v1
name: victoria-metrics-alert
description: Victoria Metrics Alert - executes a list of given MetricsQL expressions (rules) and sends alerts to Alert Manager.
version: 0.6.1
appVersion: v1.91.0
sources:
- https://github.com/VictoriaMetrics/helm-charts
