apiVersion: v2
type: application
name: victoria-metrics-alert
description: VictoriaMetrics Alert - executes a list of given MetricsQL expressions (rules) and sends alerts to Alert Manager.
version: 0.26.6
appVersion: v1.130.0
sources:
  - https://github.com/VictoriaMetrics/helm-charts
icon: https://avatars.githubusercontent.com/u/43720803?s=200&v=4
kubeVersion: ">=1.25.0-0"
home: https://github.com/VictoriaMetrics/helm-charts
keywords:
  - victoriametrics
  - vmalert
  - alerting
  - alerts
  - monitoring
  - kubernetes
  - observability
  - metrics
  - timeseries
  - rules
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/category: "monitoring-logging"
  artifacthub.io/links: |
    - name: Sources
      url: https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-alert
    - name: Charts repo
      url: https://victoriametrics.github.io/helm-charts/
    - name: Docs
      url: https://docs.victoriametrics.com/victoriametrics/vmalert/
    - name: Changelog
      url: https://docs.victoriametrics.com/victoriametrics/changelog/
dependencies:
  - name: victoria-metrics-common
    version: "0.0.*"
    repository: https://victoriametrics.github.io/helm-charts
