{{- $app := (include "victoria-metrics-k8s-stack.name" .) }}
{{- $fullname := ((printf "%s-additional-victoria-metrics-rules" (include "victoria-metrics-k8s-stack.fullname" .)) | trunc 63 | trimSuffix "-") }}
{{- if .Values.additionalVictoriaMetricsMap }}
apiVersion: v1
kind: List
metadata:
  name: {{ $fullname }}
  namespace: {{ include "vm.namespace" . }}
items:
{{- range $VMRuleName, $VMRule := .Values.additionalVictoriaMetricsMap }}
  - apiVersion: operator.victoriametrics.com/v1beta1
    kind: VMRule
    metadata:
      {{- $name := ((printf "%s-%s" $app $VMRuleName) | trunc 63 | trimSuffix "-") }}
      name: {{ $name }}
      namespace: {{ include "vm.namespace" $ }}
      {{- $extraLabels := (deepCopy ($VMRule.additionalLabels | default dict)) -}}
      {{- $_ := set $extraLabels "app" $app -}}
      {{- $ctx := dict "helm" $ "extraLabels" $extraLabels }}
      labels: {{ include "victoria-metrics-k8s-stack.labels" $ctx | nindent 8 }}
    spec:
      groups: {{ toYaml $VMRule.groups | nindent 8 }}
{{- end }}
{{- end }}
