{{- if .Values.rbac.create -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "vm-operator.fullname" . }}
  {{- $ctx := merge (deepCopy .) (dict "extraLabels" .Values.extraLabels) }}
  labels: {{ include "vm-operator.labels" $ctx | nindent 4 }}
  {{- with .Values.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ template "vm-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "vm-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
