{{- $watchNamespaces := (fromYaml (tpl (toYaml (dict "ns" .Values.watchNamespaces)) .)).ns }}
{{- $selfNamespace := .Release.Namespace }}
{{- $watchSelfNamespace := (and (eq (len $watchNamespaces) 1) (eq (first $watchNamespaces) $selfNamespace)) }}

{{- if and .Values.rbac.create (not $watchSelfNamespace) }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "vm-operator.fullname" . }}
  {{- $ctx := dict "helm" . "extraLabels" .Values.extraLabels }}
  labels: {{ include "vm-operator.labels" $ctx | nindent 4 }}
  {{- with .Values.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ template "vm-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: {{ ternary "Role" "ClusterRole"  (eq (len .Values.watchNamespaces) 1) }}
  name: {{ include "vm-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
{{- if or .Values.cleanupCRD .Values.crd.cleanup.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vm-operator.cleanupHookName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "vm-operator.labels" . | nindent 4 }}
  annotations: {{ include "vm-operator.cleanup.annotations" (dict "hookWeight" "-4") | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "vm-operator.cleanupHookName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "vm-operator.cleanupHookName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
