apiVersion: v2
type: application
name: victoria-logs-collector
description: VictoriaLogs Collector - collects logs from Kubernetes containers and stores them to VictoriaLogs
version: 0.2.0
appVersion: v1.43.0
sources:
  - https://github.com/VictoriaMetrics/helm-charts
icon: https://avatars.githubusercontent.com/u/43720803?s=200&v=4
kubeVersion: ">=1.25.0-0"
home: https://github.com/VictoriaMetrics/helm-charts
keywords:
  - victorialogs
  - logs
  - agent
  - collector
  - kubernetes
  - observability
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/category: "monitoring-logging"
  artifacthub.io/links: |
    - name: Sources
      url: https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-logs-collector
    - name: Charts repo
      url: https://victoriametrics.github.io/helm-charts/
    - name: Changelog
      url: https://docs.victoriametrics.com/changelog/
dependencies:
  - name: victoria-metrics-common
    version: "0.0.*"
    repository: https://victoriametrics.github.io/helm-charts
