{{- if and .Values.vmalert.enabled .Values.vmalert.templateFiles }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ printf "%s-%s" (include "victoria-metrics-k8s-stack.fullname" .) "vmalert-extra-tpl" | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "vm.namespace" . }}
  labels: 
    app.kubernetes.io/component: {{ include "victoria-metrics-k8s-stack.name" . }}-vmalert
    {{- include "victoria-metrics-k8s-stack.labels" . | nindent 4 }}
data:
  {{- range $file, $template := .Values.vmalert.templateFiles }}
  {{ $file }}: |{{ $template | nindent 4 }}
  {{- end }}
{{- end }}
